name: Create Notebook

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "test_main" ]
  workflow_dispatch:
      
jobs:
  create_notebook:
    environment: CopilotBuilder
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'LittleLittleCloud/CopilotBuilder'
          ref: 'main'
          token: ${{ secrets.COPILOTBUILDER_PAT }}
      - uses: actions/checkout@v3
        with:
          path: 'MLTask_101'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          source-url: ${{ vars.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }}
          
      - name: Restore dependencies
        run: dotnet restore --use-current-runtime

      - name: Build CopilotBuilder
        run: dotnet build ./src/CopilotBuilder.CodingTask/CopilotBuilder.CodingTask.csproj --configuration Release --no-restore --use-current-runtime
      
      - name: Run CopilotBuilder
        run: dotnet run --no-build --configuration Release --runtime linux-x64 --project ./src/CopilotBuilder.CodingTask/CopilotBuilder.CodingTask.csproj -- --task-folder MLTask_101
        env:
          GPT_35_API_KEY: ${{ secrets.GPT_35_API_KEY }}
          GPT_4_API_KEY: ${{ secrets.GPT_4_API_KEY }}
          GPT_35_ENDPOINT: ${{ secrets.GPT_35_ENDPOINT }}
          GPT_4_ENDPOINT: ${{ secrets.GPT_4_ENDPOINT }}

      - name: Create PR from MLTask_101 if there are changes
        run: |
          git config --global user.name "CopilotBuilder"
          git config --global user.email "g2260578356@gmail.com"
          cd MLTask_101
          # if branch name is main, then create a branch named u/cb/add_notebook_${{ github.run_id }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            git checkout -b u/cb/add_notebook_${{ github.run_id }}
          fi
          git add .
          if [[ -z $(git diff --cached --exit-code) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Add notebook from CopilotBuilder"
          git push --set-upstream origin HEAD
          gh pr create --title "Add notebook from CopilotBuilder" --body "Add notebook from CopilotBuilder" --base main --head HEAD --repo LittleLittleCloud/MLTask_101 --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





